In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[ 1.5556699 ,  0.55027241,  1.53496805, ...,  1.65379316,
         1.74965609, -0.29087731],
       [-0.18588479, -1.19084743, -0.19245524, ...,  0.26853046,
         0.4750613 ,  0.46708019],
       [ 1.04245813, -1.38049697,  0.91426405, ..., -0.48568485,
        -1.77495689, -1.39282263],
       ...,
       [ 3.91980937, -0.18319146,  3.91230494, ...,  0.66001775,
        -1.98531178, -1.57908207],
       [-0.85614497, -1.04232671, -0.88658893, ..., -1.093243  ,
        -1.58953296, -0.61656218],
       [ 0.22075841, -0.99205816,  0.17793871, ..., -0.01454496,
        -0.36480006, -0.09977297]], shape=(455, 30))

In [10]:
y_train

343    M
482    B
491    B
102    B
67     B
      ..
247    B
56     M
212    M
173    B
472    B
Name: diagnosis, Length: 455, dtype: str

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_train

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0])

### Numpy Array To Tensor

In [13]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

### Defining the model

In [14]:
class MySimpleNN():
    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1,dtype=torch.float64, requires_grad = True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad = True)
    
    def forward(self, X):
         z = torch.matmul(X, self.weights) + self.bias
         y_pred = torch.sigmoid(z)
         return y_pred
    
    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

### Parameters

In [15]:
learning_rate = 0.1
epochs = 100

### Training pipeline

In [16]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.6414495675668404
Epoch: 2, Loss: 3.522514962358461
Epoch: 3, Loss: 3.399123074781063
Epoch: 4, Loss: 3.2702158497358895
Epoch: 5, Loss: 3.140442574771798
Epoch: 6, Loss: 3.0041420783180235
Epoch: 7, Loss: 2.8683460854114133
Epoch: 8, Loss: 2.724233615726743
Epoch: 9, Loss: 2.5779313492762754
Epoch: 10, Loss: 2.433675392212436
Epoch: 11, Loss: 2.291273089761607
Epoch: 12, Loss: 2.1466332817396814
Epoch: 13, Loss: 2.0030122178779872
Epoch: 14, Loss: 1.856441211835724
Epoch: 15, Loss: 1.7171066764943252
Epoch: 16, Loss: 1.5881336398284918
Epoch: 17, Loss: 1.4695130693239713
Epoch: 18, Loss: 1.3597072776675994
Epoch: 19, Loss: 1.2622934364098315
Epoch: 20, Loss: 1.1771777368427327
Epoch: 21, Loss: 1.1038353622120023
Epoch: 22, Loss: 1.0413439999368492
Epoch: 23, Loss: 0.9885042184383988
Epoch: 24, Loss: 0.9440065260611976
Epoch: 25, Loss: 0.9065799998491204
Epoch: 26, Loss: 0.8750814944501363
Epoch: 27, Loss: 0.8485268594023692
Epoch: 28, Loss: 0.8260883713073304
Epoch: 29, Loss: 0.8070792113862203
Epoch: 30, Loss: 0.790933986616146
Epoch: 31, Loss: 0.7771882644461674
Epoch: 32, Loss: 0.7654593002040159
Epoch: 33, Loss: 0.7554296139303467
Epoch: 34, Loss: 0.7468339076136409
Epoch: 35, Loss: 0.739449012985083
Epoch: 36, Loss: 0.7330862994307149
Epoch: 37, Loss: 0.7275859474135624
Epoch: 38, Loss: 0.7228125494687756
Epoch: 39, Loss: 0.7186516058410177
Epoch: 40, Loss: 0.7150066084970774
Epoch: 41, Loss: 0.71179652358496
Epoch: 42, Loss: 0.7089535691380477
Epoch: 43, Loss: 0.7064212388144878
Epoch: 44, Loss: 0.7041525501452656
Epoch: 45, Loss: 0.7021085062356863
Epoch: 46, Loss: 0.7002567610418874
Epoch: 47, Loss: 0.6985704757099784
Epoch: 48, Loss: 0.6970273501981739
Epoch: 49, Loss: 0.6956088119944511
Epoch: 50, Loss: 0.6942993426482059
Epoch: 51, Loss: 0.693085922968232
Epoch: 52, Loss: 0.6919575787973723
Epoch: 53, Loss: 0.6909050109151201
Epoch: 54, Loss: 0.6899202945488206
Epoch: 55, Loss: 0.6889966359721215
Epoch: 56, Loss: 0.688128175589689
Epoch: 57, Loss: 0.6873098286640971
Epoch: 58, Loss: 0.6865371563930099
Epoch: 59, Loss: 0.6858062613811695
Epoch: 60, Loss: 0.6851137026799096
Epoch: 61, Loss: 0.6844564265048995
Epoch: 62, Loss: 0.6838317095133288
Epoch: 63, Loss: 0.6832371121485968
Epoch: 64, Loss: 0.6826704400666627
Epoch: 65, Loss: 0.682129712064294
Epoch: 66, Loss: 0.6816131332536485
Epoch: 67, Loss: 0.6811190724854985
Epoch: 68, Loss: 0.6806460432278582
Epoch: 69, Loss: 0.6801926872685553
Epoch: 70, Loss: 0.679757760738093
Epoch: 71, Loss: 0.6793401220500228
Epoch: 72, Loss: 0.6789387214356835
Epoch: 73, Loss: 0.6785525918130179
Epoch: 74, Loss: 0.6781808407788703
Epoch: 75, Loss: 0.6778226435535135
Epoch: 76, Loss: 0.6774772367373626
Epoch: 77, Loss: 0.677143912764686
Epoch: 78, Loss: 0.6768220149589596
Epoch: 79, Loss: 0.6765109331104296
Epoch: 80, Loss: 0.6762100995092634
Epoch: 81, Loss: 0.675918985378057
Epoch: 82, Loss: 0.6756370976559292
Epoch: 83, Loss: 0.675363976093363
Epoch: 84, Loss: 0.6750991906226738
Epoch: 85, Loss: 0.6748423389737387
Epoch: 86, Loss: 0.6745930445085877
Epoch: 87, Loss: 0.6743509542517977
Epoch: 88, Loss: 0.674115737096467
Epoch: 89, Loss: 0.6738870821679565
Epoch: 90, Loss: 0.6736646973296548
Epoch: 91, Loss: 0.6734483078168124
Epoch: 92, Loss: 0.6732376549860345
Epoch: 93, Loss: 0.673032495169376
Epoch: 94, Loss: 0.6728325986231579
Epoch: 95, Loss: 0.6726377485626657
Epoch: 96, Loss: 0.6724477402748028
Epoch: 97, Loss: 0.6722623803015801
Epoch: 98, Loss: 0.6720814856880429
Epoch: 99, Loss: 0.6719048832888714
Epoch: 100, Loss: 0.6717324091284608

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6140350699424744

In [18]:
y_pred

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])